apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ud55fkn4r-go
  janus-idp.io/tekton: ud55fkn4r-go
  backstage.io/kubernetes-id: ud55fkn4r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ud55fkn4r-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
